# Generated by Django 4.0.4 on 2022-05-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='arma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_arma', models.CharField(max_length=64)),
                ('modelo_arma', models.CharField(max_length=64)),
                ('quantidade_tiros', models.IntegerField()),
                ('valor_estimado_arma', models.FloatField()),
                ('imagem', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='calibre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibre', models.CharField(choices=[('38', 'calibre .38'), ('380', 'calibre .380'), ('40', 'calibre .40'), ('45', 'calibre .45')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='objeto_tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto', models.CharField(choices=[('A', 'Arma'), ('M', 'Munição')], max_length=1)),
            ],
        ),
    ]
