# Generated by Django 4.0.4 on 2022-05-12 17:15

from django.db import migrations, models
import objetos.models


class Migration(migrations.Migration):

    dependencies = [
        ('objetos', '0003_alter_municao_calibre_municao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=objetos.models.upload_image_arma),
        ),
    ]
